export const PROVIDER_TYPES = [
  'APRN', 'ARNP', 'CNS', 'CRNA', 'DC',
  'DDS', 'DMD', 'DO', 'DPM', 'LCMFT',
  'LCMHC', 'LCP', 'LCPC', 'MD', 'NP',
  'PA'
];

export const PROVIDER_STAFF_STATUS = [
  'ACTIVE', 'AFFILIATE', 'ASSOCIATE', 'COMMUNITY',
  'CONSULTING', 'COURTESY', 'FACULTY', 'HONORARY',
  'HOSPITALIST', 'HOUSE_STAFF', 'LOCUM_TENENS', 'PROVISIONAL',
  'RESIDENT', 'TEACHING'
];

export const PROVIDER_STATUS = [
  'AWAITING_CREDENTIALS', 'READY_FOR_REVIEW', 'UNDER_REVIEW',
  'AWAITING_DECISION', 'APPROVED', 'DENIED'
];
